### ISSUE TITLE
Error executing the go runner

### ISSUE THREAD

**Issue by rbel** [square/shift#20]
Hi,

I'm trying to setup Shift but i'm getting the next error when starting the runner:

I0627 09:54:37.607786 14755 runner.go:173] Getting staged migrations.
E0627 09:54:37.607975 14755 runner.go:176] Failed to get staged migrations (error: rest: error getting staged migrations)

I'm sure that the API url is configured correct in the configuration.

Any idea how to debug this issue?

**Comment by michaelfinch** [comment]
Hey rebel. Just merged a change to make the errors in the "rest" package (which talks to the API) more useful. Can you pull down the latest, try again, and post the logs here? We're still working on improving the bootstrapping process, so I appreciate your help

**Comment by rbel** [comment]
Helped me debugging the issue:

```
I0705 17:00:28.583447 19377 runner.go:237] Getting staged migrations.
I0705 17:00:28.615358 19377 runner.go:244] No new staged migrations.
I0705 17:00:45.615488 19377 runner.go:237] Getting staged migrations.
I0705 17:00:45.620124 19377 runner.go:244] No new staged migrations.
```

Could you let me know how to run the runner in "production" environment?

Also is it possible to write any documentation how to inject data into the database?
Does it has to be done by hand or is there functionality in the web ui?
At this point the app runs (with passenger) but we have no clue how to start "configuring" it.

**Comment by michaelfinch** [comment]
@rbel I just updated the docs to hopefully answer your questions (you can see the changes here: https://github.com/square/shift/pull/26/files).

It seems like you've got the rails app up and running, and the runner is communicating with it. The next thing you should do is create some clusters, and then try filing and running migrations against those clusters. Happy to chat on slack or something if that'd be useful to you.

**Comment by rbel** [comment]
Sure as I'm still missing some info to finish the setup. Is Skype okay for you? How will we exchange info?

**Comment by michaelfinch** [comment]
Yeah, message me on skype at michaelfinch9
